### ISSUE TITLE
$SWEEP_METHOD output to CLI is split

### ISSUE THREAD

**Issue by astryzia** [astryzia/bash-portscanner#11]
Rather than being all in one line, these are printed separately.

Sample output:
```bash
[+] Sweeping for live hosts (ICMP)

[+] Sweeping for live hosts (+)

[+] Sweeping for live hosts (ARP)
[+] 44 hosts found
[+] Beginning scan of 1 total ports
```

**Comment by muschem** [comment]
Oops. Didn't test that case... must have broken it along the way. Will take a look now.

**Comment by astryzia** [comment]
It only does this when using the `-r` flag

**Comment by muschem** [comment]
ah. problem with string substitution. i'll get a fix committed soon.

**Comment by muschem** [comment]
PR #14 opened. One solution provided, and a couple alternate approaches described in the comments.

**Comment by astryzia** [comment]
Rolling in with an upcoming push instead of merging
