### ISSUE TITLE
Add service descriptions for well-known ports?

### ISSUE THREAD

**Issue by muschem** [astryzia/bash-portscanner#13]
For example:
PORT    SERVICE
22/tcp    ssh
80/tcp    http

etc.

These would be pre-defined and statically mapped, not dynamically determined (at least not initially). So, if someone was using 8080 for ssh, the output would not not indicate the actual use, but rather the more common use (http-alt or http-proxy in this example). 

Is this something you'd like to add? My understanding is that nmap (https://nmap.org/book/nmap-services.html) originally based theirs on the IANA list (https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt), but over the years it has grown/evolved a bit. A couple of different approaches might work, but I was thinking of creating a separate services file containing the port numbers and descriptions, which could easily be referenced by the script. We could use IANA if referencing from nmap is not desirable.

**Comment by astryzia** [comment]
Definitely! The more detail the better. I think the new addition of libraries will make this nice and neat and be a great use case. Let me know what parts I can help you work on so we don't duplicate efforts.

**Comment by muschem** [comment]
Solution offered in PR #16
