### ISSUE TITLE
Default port list broken?

### ISSUE THREAD

**Issue by muschem** [astryzia/bash-portscanner#15]
The new libraries version doesn't seem to work without specifying ports. Looking into this now. Expected functionality was to scan a default list of port (top 20 unless otherwise indicated), unless the -p flag overrides the default list. Running with no flags scans 0 ports for me now.

**Comment by muschem** [comment]
oh... maybe bash can't export arrays? that's no fun. a couple solutions might work:
1. move tcp_ports array back into portscan.sh script; or
2. change the construction of the ports list, such that an array isn't used

**Comment by muschem** [comment]
`readarray` works if the ports are listed in a flat file, but that was introduced around bash v4.0. how far back are we aiming for in terms of compatibility?

**Comment by astryzia** [comment]
I haven't given much thought to backwards compatibility -- will think on this and open to suggestions.

**Comment by astryzia** [comment]
More on above: There wasn't really a roadmap I had in mind for this when I made the very first commit, but I think with its current complexity it's worthwhile to think on.

**Comment by astryzia** [comment]
> Looks like there are issues directly referencing arrays in separate files like this. Apparently, exporting arrays wasn't officially supported in bash up until around v4.3 or so. Keeping the current approach might break use-case on some older systems. Some options:
> 
> 1. move tcp_ports array back into core.sh script; or
> 2. change the construction of the ports list, such that an array isn't used
> 3. figure out a portable work-around for using array mostly as-is
> 
> I probably don't have time to fix immediately. I'll pick this up later if it is still open.

For now I've moved the tcp_ports array back into core.sh and pushed in commit ab6298a5cd42ce094824012bc533846e2dec47d1

**Comment by astryzia** [comment]
After some thought, maybe keeping this as a single script is a better idea since its purpose is simplicity and compatibility on limited systems. What are your thoughts?

**Comment by muschem** [comment]
Sorry for any typos - eyes currently dilated. I can see it both ways. Dividing it up makes it easier to manage additional complexity and add fun new features. On the other hand, if I just want to copy/pasta a script onto a target that lacks nmap, unicorn, netcat, or other tools that do this, then yeah... I'd probably find a monolithic script easier for that. I'm happy to help either way you want to go.

**Comment by muschem** [comment]
I did have a chance to test a potential fix, if you want to keep the separate library approach... 

I put the ports into a flat file, similar to how they are now, but without the array - just port numbers delimited by space. Then, in core.sh I read that file into a local array with:

`tcp_ports=($(cat lib/tcp_ports.sh))` 

This works, and seems portable (doesn't use any special bash functions only available in recent versions). So, that might be an option if you want. I'm not going to say that it looks clean, but sometimes ugly code is ok :)

**Comment by muschem** [comment]
Feel free to ignore the last couple of PRs if you decide you prefer to condense back to a monolithic script. I definitely see the advantages of going the library route. I wonder... what would you think about continuing down the library path, but perhaps creating a helper script at some point to allow users to re-generate a monolithic solution if they require/prefer one? Might be the best of both worlds, though a bit more maintenance overhead.

**Comment by astryzia** [comment]
I'm going to get caught up on everything this morning. I think that's definitely the best route forward -- splitting out into libraries and then the helper script to unify everything for that use-case. Having things separated out for development makes me a lot less stressed about all the added complexity.
