### ISSUE TITLE
Default handling for multi-homed machines?

### ISSUE THREAD

**Issue by muschem** [astryzia/bash-portscanner#4]
Current behavior ignores any additional non-loopback network interfaces beyond the default, which excludes networks in a multi-homed scenario. This may be intentional, but if not, consideration could be given to cases with multiple physical interfaces, virtual interfaces, bridged interfaces and potentially other scenarios.

**Comment by muschem** [comment]
Honestly, this default is probably fine. More complex scan scenarios could be covered by adding input option for custom IP ranges, rather than spend time accounting for this edge case.

**Comment by astryzia** [comment]
I agree on input options being the best solution here for now. It's likely ideal for a lot of users to have the granularity of custom IP ranges rather than only "aim and fire" as it's currently configured.

**Comment by muschem** [comment]
Happy to close this one out, then. I had planned to expand the existing option for a single host input to handle a range of hosts soon.
